### PR TITLE
Add Azure DNS Provider

### PR DESCRIPTION
**Pull request by kurokobo**
#24

These implementation (also available at [my repo](https://github.com/kurokobo/libdns-azure)) and related [caddy-dns module](https://github.com/kurokobo/caddy-dns-azure) is already working with Caddy in my private environment for my personal use.
It would be great if you could review this PR.

### CODE REVIEW

**Comment by kurokobo** [comment]
I forgot to change the name and year in the LICENSE :(
I just fixed it so it's ready for review now, thank you.

**Comment by mholt** [comment]
Thanks for implementing a provider!

I see a few things that will need to be resolved or clarified. First, see [the requirements here](https://github.com/libdns/libdns/wiki/Implementing-providers#requirements):

> Configuration must be primarily through struct fields. Environment variables are allowed, but should only be used as defaults.

It looks like you accept env variables but do not require them, is that right? If so, that's OK; as long as it be configured without env vars.

> Explicit/exported provisioning steps should be avoided. They break a provider's drop-in-replacement-ability with other providers because the user has to know to first provision certain types before using them. Instead of requiring explicit provisioning, try to do it implicitly in each exported method that relies on it. If provisioning is expensive, it can be done just once by storing it in the struct (this requires synchronization for thread-safety) or by using sync.Once (which does the synchronization for you) the first time it is needed.

I see there's a `NewClient()` method, unfortunately this won't fly (if I am understanding it right). It has to be able to be used without a separate function call first. Other providers often do this by calling a function (synced by a mutex) at the beginning of each exported method to ensure the client is set up before it tries to do anything.

At a glance, tests and other things look good though!

**Comment by kurokobo** [comment]
Thanks for taking your time and the quick review!

> It looks like you accept env variables but do not require them, is that right? If so, that's OK; as long as it be configured without env vars.

No, all configurations need to be explicit in structure fields. My implementation uses `azure-go-sdk` and it has the ability to authenticate using environment variables, but my implementation does not use that feature.
I think my README and example might be the cause of the confusion. I'll fix the description.

> I see there's a NewClient() method, unfortunately this won't fly (if I am understanding it right).

Ah, you are right.
I was referring to the route53 implementation (that has `NewSession()`), but now I understand your concern. I will fix it.

Please give me some time to fix it. Thank you.

**Comment by kurokobo** [comment]
I've fixed that. Could you please check this again?

**Review by mholt — APPROVED** [review]
Looks much better! Thanks for clarifying/fixing.

I'll make a repo for this at `libdns/azure` -- sound good?

Also, would you be willing to contribute your Caddy plugin to the `caddy-dns/azure` repo which I will make soon?

**Comment by kurokobo** [comment]
Thanks for your review! I'm glad it's approved :)

I have received the two invitations. I will push the code to both libdns and caddy-dns in probably today, or in a few days at the latest.

**Pull request closed without merging**
