### PR TITLE
Add pdns provider

### LINKED ISSUE #45: pdns provider
I have initial support for a powerdns (pdns) libdns provider.  PR incoming.

### PR DESCRIPTION
**Pull request by nathanejohnson**
Closes #45

I'm a little unsure of how to structure the PR since the original repository was created from the template, so I just forked libdns and copied the files into a subdirectory.  It won't work exactly as-is because the module name still expects the old repository import path at github.com/nathanejohnson/pdnsprovider

Thanks

### CODE REVIEW

**Comment by mholt** [comment]
Cool; at a glance, this seems to meet all the major requirements.

Let me know when you're ready for a final review.

**Comment by nathanejohnson** [comment]
> Let me know when you're ready for a final review.

I think it's basically ready for a look, I don't have any github actions CI stuff set up but I was going to wait until it had a place to live first.

**Comment by mholt** [comment]
Great, thanks. Adding the repo now. Make sure to update the module path to match the final resting place.

Would you be interested in making a [caddy-dns](https://github.com/caddy-dns) module as well so that it can be used within Caddy? (I'll make the repo either way, it'll just be empty until someone picks it up.)

**Review by mholt — APPROVED** [review]

**Comment by nathanejohnson** [comment]
> Great, thanks. Adding the repo now. Make sure to update the module path to match the final resting place.

Thanks, and will do

> Would you be interested in making a caddy-dns module as well so that it can be used within Caddy?

Sure, as soon as I figure out how to :)

**Pull request closed without merging**
